(*                                                                            *)
(* File generated by the B&R AS 4 control config generator                    *)
(*                                                                            *)
(*     Provider: machineering                                                 *)
(*  Application: iPhysics_2.4.master                                          *)
(* Architecture: Windows 64 Bit                                               *)
(*      Version: 2.4.12706.master                                             *)
(*        Build: 608a88cb4                                                    *)
(*         Date: 2022-07-25, Time: 11:40:12                                   *)
(*                                                                            *)

TYPE
ComTotal_INPUTS_32BIT : STRUCT



		NumSignals	: INT := 24;

        CapPusher_LBK : BOOL := 0;
        (* BOOL CapPusher_LBK *)
        CapPusher_LFR : BOOL := 0;
        (* BOOL CapPusher_LFR *)
        MagazineEmpty_IR : BOOL := 0;
        (* BOOL MagazineEmpty_IR *)
        CapAtPickup_IR : BOOL := 0;
        (* BOOL CapAtPickup_IR *)
        ColourDetection_IR : BOOL := 0;
        (* BOOL ColourDetection_IR *)
        CapColour_NOT_BLACK : BOOL := 0;
        (* BOOL CapColour_NOT_BLACK *)
        CapColour_METALLIC : BOOL := 0;
        (* BOOL CapColour_METALLIC *)
        SortingConveyorStart_IR : BOOL := 0;
        (* BOOL SortingConveyorStart_IR *)
        LogoConveyorStart_IR : BOOL := 0;
        (* BOOL LogoConveyorStart_IR *)
        LogoConveyorExit_IR : BOOL := 0;
        (* BOOL LogoConveyorExit_IR *)
        LaneGate1_LBK : BOOL := 0;
        (* BOOL LaneGate1_LBK *)
        LaneGate1_LFR : BOOL := 0;
        (* BOOL LaneGate1_LFR *)
        LaneGate2_LBK : BOOL := 0;
        (* BOOL LaneGate2_LBK *)
        LaneGate2_LFR : BOOL := 0;
        (* BOOL LaneGate2_LFR *)
        PickupArm_LBK : BOOL := 0;
        (* BOOL PickupArm_LBK *)
        PickupArm_LFR : BOOL := 0;
        (* BOOL PickupArm_LFR *)
        CapGripper_VACUUM : BOOL := 0;
        (* BOOL CapGripper_VACUUM *)
        LaneTop_IR : BOOL := 0;
        (* BOOL LaneTop_IR *)
        LogoAxis_ACTPOS : REAL := 0.0;
        (* REAL LogoAxis_ACTPOS *)
        LogoStamper_LBK : BOOL := 0;
        (* BOOL LogoStamper_LBK *)
        LogoStamper_LFR : BOOL := 0;
        (* BOOL LogoStamper_LFR *)
        PuncherAxis_ACTPOS : REAL := 0.0;
        (* REAL PuncherAxis_ACTPOS *)
        HolePuncher_LBK : BOOL := 0;
        (* BOOL HolePuncher_LBK *)
        HolePuncher_LFR : BOOL := 0;
        (* BOOL HolePuncher_LFR *)

	END_STRUCT;

ComTotal_OUTPUTS_32BIT : STRUCT


		NumSignals	: INT := 19;

        CapPusher_FWD : BOOL := 0;
        (* BOOL CapPusher_FWD *)
        SortingConveyor_SETSPEED : REAL := 0.0;
        (* REAL SortingConveyor_SETSPEED *)
        SortingConveyor_CLEAR : BOOL := 0;
        (* BOOL SortingConveyor_CLEAR *)
        LogoConveyor_SETSPEED : REAL := 0.0;
        (* REAL LogoConveyor_SETSPEED *)
        LogoConveyor_CLEAR : BOOL := 0;
        (* BOOL LogoConveyor_CLEAR *)
        LaneGate1_FWD : BOOL := 0;
        (* BOOL LaneGate1_FWD *)
        LaneGate2_FWD : BOOL := 0;
        (* BOOL LaneGate2_FWD *)
        LaneStopper1_CLEAR : BOOL := 0;
        (* BOOL LaneStopper1_CLEAR *)
        LaneStopper2_CLEAR : BOOL := 0;
        (* BOOL LaneStopper2_CLEAR *)
        LaneStopper3_CLEAR : BOOL := 0;
        (* BOOL LaneStopper3_CLEAR *)
        PickupArm_FWD : BOOL := 0;
        (* BOOL PickupArm_FWD *)
        PickupArm_BWD : BOOL := 0;
        (* BOOL PickupArm_BWD *)
        CapGripper_PICK : BOOL := 0;
        (* BOOL CapGripper_PICK *)
        CapStopper_FWD : BOOL := 0;
        (* BOOL CapStopper_FWD *)
        CP1586_PRESS : BOOL := 0;
        (* BOOL CP1586_PRESS *)
        LogoAxis_SETPOS : REAL := 0.0;
        (* REAL LogoAxis_SETPOS *)
        LogoStamper_FWD : BOOL := 0;
        (* BOOL LogoStamper_FWD *)
        PuncherAxis_SETPOS : REAL := 0.0;
        (* REAL PuncherAxis_SETPOS *)
        HolePuncher_FWD : BOOL := 0;
        (* BOOL HolePuncher_FWD *)

	END_STRUCT;


END_TYPE
